// ccom_rx.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module ccom_rx (
		input  wire        clk50_clk,       //   clk50.clk
		input  wire [23:0] dxdy_export,     //    dxdy.export
		input  wire [23:0] qpdp1_export,    //   qpdp1.export
		input  wire [23:0] qpdp2_export,    //   qpdp2.export
		input  wire        reset_n_reset_n, // reset_n.reset_n
		input  wire [7:0]  status_export    //  status.export
	);

	wire         pll_0_outclk0_clk;                                              // pll_0:outclk_0 -> [intel_niosv_m_0:clk, irq_mapper:clk, jtag_uart_0:clk, mm_interconnect_0:pll_0_outclk0_clk, onchip_memory2_0:clk, pio_dxdy:clk, pio_qpdp1:clk, pio_qpdp2:clk, pio_status:clk, rst_controller:clk]
	wire         intel_niosv_m_0_dbg_reset_out_reset;                            // intel_niosv_m_0:dbg_reset_out_reset -> intel_niosv_m_0:ndm_reset_in_reset
	wire  [31:0] intel_niosv_m_0_data_manager_readdata;                          // mm_interconnect_0:intel_niosv_m_0_data_manager_readdata -> intel_niosv_m_0:data_manager_readdata
	wire         intel_niosv_m_0_data_manager_waitrequest;                       // mm_interconnect_0:intel_niosv_m_0_data_manager_waitrequest -> intel_niosv_m_0:data_manager_waitrequest
	wire  [31:0] intel_niosv_m_0_data_manager_address;                           // intel_niosv_m_0:data_manager_address -> mm_interconnect_0:intel_niosv_m_0_data_manager_address
	wire         intel_niosv_m_0_data_manager_read;                              // intel_niosv_m_0:data_manager_read -> mm_interconnect_0:intel_niosv_m_0_data_manager_read
	wire   [3:0] intel_niosv_m_0_data_manager_byteenable;                        // intel_niosv_m_0:data_manager_byteenable -> mm_interconnect_0:intel_niosv_m_0_data_manager_byteenable
	wire         intel_niosv_m_0_data_manager_readdatavalid;                     // mm_interconnect_0:intel_niosv_m_0_data_manager_readdatavalid -> intel_niosv_m_0:data_manager_readdatavalid
	wire   [1:0] intel_niosv_m_0_data_manager_response;                          // mm_interconnect_0:intel_niosv_m_0_data_manager_response -> intel_niosv_m_0:data_manager_response
	wire         intel_niosv_m_0_data_manager_write;                             // intel_niosv_m_0:data_manager_write -> mm_interconnect_0:intel_niosv_m_0_data_manager_write
	wire  [31:0] intel_niosv_m_0_data_manager_writedata;                         // intel_niosv_m_0:data_manager_writedata -> mm_interconnect_0:intel_niosv_m_0_data_manager_writedata
	wire         intel_niosv_m_0_data_manager_writeresponsevalid;                // mm_interconnect_0:intel_niosv_m_0_data_manager_writeresponsevalid -> intel_niosv_m_0:data_manager_writeresponsevalid
	wire  [31:0] intel_niosv_m_0_instruction_manager_readdata;                   // mm_interconnect_0:intel_niosv_m_0_instruction_manager_readdata -> intel_niosv_m_0:instruction_manager_readdata
	wire         intel_niosv_m_0_instruction_manager_waitrequest;                // mm_interconnect_0:intel_niosv_m_0_instruction_manager_waitrequest -> intel_niosv_m_0:instruction_manager_waitrequest
	wire  [31:0] intel_niosv_m_0_instruction_manager_address;                    // intel_niosv_m_0:instruction_manager_address -> mm_interconnect_0:intel_niosv_m_0_instruction_manager_address
	wire         intel_niosv_m_0_instruction_manager_read;                       // intel_niosv_m_0:instruction_manager_read -> mm_interconnect_0:intel_niosv_m_0_instruction_manager_read
	wire         intel_niosv_m_0_instruction_manager_readdatavalid;              // mm_interconnect_0:intel_niosv_m_0_instruction_manager_readdatavalid -> intel_niosv_m_0:instruction_manager_readdatavalid
	wire   [1:0] intel_niosv_m_0_instruction_manager_response;                   // mm_interconnect_0:intel_niosv_m_0_instruction_manager_response -> intel_niosv_m_0:instruction_manager_response
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect;     // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_chipselect -> jtag_uart_0:av_chipselect
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata;       // jtag_uart_0:av_readdata -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest;    // jtag_uart_0:av_waitrequest -> mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address;        // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_address -> jtag_uart_0:av_address
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read;           // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_read -> jtag_uart_0:av_read_n
	wire         mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write;          // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_write -> jtag_uart_0:av_write_n
	wire  [31:0] mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata;      // mm_interconnect_0:jtag_uart_0_avalon_jtag_slave_writedata -> jtag_uart_0:av_writedata
	wire  [31:0] mm_interconnect_0_intel_niosv_m_0_dm_agent_readdata;            // intel_niosv_m_0:dm_agent_readdata -> mm_interconnect_0:intel_niosv_m_0_dm_agent_readdata
	wire         mm_interconnect_0_intel_niosv_m_0_dm_agent_waitrequest;         // intel_niosv_m_0:dm_agent_waitrequest -> mm_interconnect_0:intel_niosv_m_0_dm_agent_waitrequest
	wire  [15:0] mm_interconnect_0_intel_niosv_m_0_dm_agent_address;             // mm_interconnect_0:intel_niosv_m_0_dm_agent_address -> intel_niosv_m_0:dm_agent_address
	wire         mm_interconnect_0_intel_niosv_m_0_dm_agent_read;                // mm_interconnect_0:intel_niosv_m_0_dm_agent_read -> intel_niosv_m_0:dm_agent_read
	wire         mm_interconnect_0_intel_niosv_m_0_dm_agent_readdatavalid;       // intel_niosv_m_0:dm_agent_readdatavalid -> mm_interconnect_0:intel_niosv_m_0_dm_agent_readdatavalid
	wire         mm_interconnect_0_intel_niosv_m_0_dm_agent_write;               // mm_interconnect_0:intel_niosv_m_0_dm_agent_write -> intel_niosv_m_0:dm_agent_write
	wire  [31:0] mm_interconnect_0_intel_niosv_m_0_dm_agent_writedata;           // mm_interconnect_0:intel_niosv_m_0_dm_agent_writedata -> intel_niosv_m_0:dm_agent_writedata
	wire         mm_interconnect_0_onchip_memory2_0_s1_chipselect;               // mm_interconnect_0:onchip_memory2_0_s1_chipselect -> onchip_memory2_0:chipselect
	wire  [31:0] mm_interconnect_0_onchip_memory2_0_s1_readdata;                 // onchip_memory2_0:readdata -> mm_interconnect_0:onchip_memory2_0_s1_readdata
	wire  [15:0] mm_interconnect_0_onchip_memory2_0_s1_address;                  // mm_interconnect_0:onchip_memory2_0_s1_address -> onchip_memory2_0:address
	wire   [3:0] mm_interconnect_0_onchip_memory2_0_s1_byteenable;               // mm_interconnect_0:onchip_memory2_0_s1_byteenable -> onchip_memory2_0:byteenable
	wire         mm_interconnect_0_onchip_memory2_0_s1_write;                    // mm_interconnect_0:onchip_memory2_0_s1_write -> onchip_memory2_0:write
	wire  [31:0] mm_interconnect_0_onchip_memory2_0_s1_writedata;                // mm_interconnect_0:onchip_memory2_0_s1_writedata -> onchip_memory2_0:writedata
	wire         mm_interconnect_0_onchip_memory2_0_s1_clken;                    // mm_interconnect_0:onchip_memory2_0_s1_clken -> onchip_memory2_0:clken
	wire  [31:0] mm_interconnect_0_pio_qpdp1_s1_readdata;                        // pio_qpdp1:readdata -> mm_interconnect_0:pio_qpdp1_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_qpdp1_s1_address;                         // mm_interconnect_0:pio_qpdp1_s1_address -> pio_qpdp1:address
	wire  [31:0] mm_interconnect_0_pio_qpdp2_s1_readdata;                        // pio_qpdp2:readdata -> mm_interconnect_0:pio_qpdp2_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_qpdp2_s1_address;                         // mm_interconnect_0:pio_qpdp2_s1_address -> pio_qpdp2:address
	wire  [31:0] mm_interconnect_0_pio_dxdy_s1_readdata;                         // pio_dxdy:readdata -> mm_interconnect_0:pio_dxdy_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_dxdy_s1_address;                          // mm_interconnect_0:pio_dxdy_s1_address -> pio_dxdy:address
	wire  [31:0] mm_interconnect_0_pio_status_s1_readdata;                       // pio_status:readdata -> mm_interconnect_0:pio_status_s1_readdata
	wire   [1:0] mm_interconnect_0_pio_status_s1_address;                        // mm_interconnect_0:pio_status_s1_address -> pio_status:address
	wire  [31:0] mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_readdata;      // intel_niosv_m_0:timer_sw_agent_readdata -> mm_interconnect_0:intel_niosv_m_0_timer_sw_agent_readdata
	wire         mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_waitrequest;   // intel_niosv_m_0:timer_sw_agent_waitrequest -> mm_interconnect_0:intel_niosv_m_0_timer_sw_agent_waitrequest
	wire   [5:0] mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_address;       // mm_interconnect_0:intel_niosv_m_0_timer_sw_agent_address -> intel_niosv_m_0:timer_sw_agent_address
	wire         mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_read;          // mm_interconnect_0:intel_niosv_m_0_timer_sw_agent_read -> intel_niosv_m_0:timer_sw_agent_read
	wire   [3:0] mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_byteenable;    // mm_interconnect_0:intel_niosv_m_0_timer_sw_agent_byteenable -> intel_niosv_m_0:timer_sw_agent_byteenable
	wire         mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_readdatavalid; // intel_niosv_m_0:timer_sw_agent_readdatavalid -> mm_interconnect_0:intel_niosv_m_0_timer_sw_agent_readdatavalid
	wire         mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_write;         // mm_interconnect_0:intel_niosv_m_0_timer_sw_agent_write -> intel_niosv_m_0:timer_sw_agent_write
	wire  [31:0] mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_writedata;     // mm_interconnect_0:intel_niosv_m_0_timer_sw_agent_writedata -> intel_niosv_m_0:timer_sw_agent_writedata
	wire         irq_mapper_receiver0_irq;                                       // jtag_uart_0:av_irq -> irq_mapper:receiver0_irq
	wire  [15:0] intel_niosv_m_0_platform_irq_rx_irq;                            // irq_mapper:sender_irq -> intel_niosv_m_0:platform_irq_rx_irq
	wire         rst_controller_reset_out_reset;                                 // rst_controller:reset_out -> [intel_niosv_m_0:reset_reset, irq_mapper:reset, jtag_uart_0:rst_n, mm_interconnect_0:intel_niosv_m_0_reset_reset_bridge_in_reset_reset, onchip_memory2_0:reset, pio_dxdy:reset_n, pio_qpdp1:reset_n, pio_qpdp2:reset_n, pio_status:reset_n, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                             // rst_controller:reset_req -> [onchip_memory2_0:reset_req, rst_translator:reset_req_in]

	ccom_rx_intel_niosv_m_0 intel_niosv_m_0 (
		.clk                               (pll_0_outclk0_clk),                                              //                 clk.clk
		.reset_reset                       (rst_controller_reset_out_reset),                                 //               reset.reset
		.platform_irq_rx_irq               (intel_niosv_m_0_platform_irq_rx_irq),                            //     platform_irq_rx.irq
		.ndm_reset_in_reset                (intel_niosv_m_0_dbg_reset_out_reset),                            //        ndm_reset_in.reset
		.timer_sw_agent_address            (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_address),       //      timer_sw_agent.address
		.timer_sw_agent_byteenable         (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_byteenable),    //                    .byteenable
		.timer_sw_agent_read               (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_read),          //                    .read
		.timer_sw_agent_readdata           (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_readdata),      //                    .readdata
		.timer_sw_agent_write              (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_write),         //                    .write
		.timer_sw_agent_writedata          (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_writedata),     //                    .writedata
		.timer_sw_agent_waitrequest        (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_waitrequest),   //                    .waitrequest
		.timer_sw_agent_readdatavalid      (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_readdatavalid), //                    .readdatavalid
		.instruction_manager_readdata      (intel_niosv_m_0_instruction_manager_readdata),                   // instruction_manager.readdata
		.instruction_manager_waitrequest   (intel_niosv_m_0_instruction_manager_waitrequest),                //                    .waitrequest
		.instruction_manager_readdatavalid (intel_niosv_m_0_instruction_manager_readdatavalid),              //                    .readdatavalid
		.instruction_manager_response      (intel_niosv_m_0_instruction_manager_response),                   //                    .response
		.instruction_manager_address       (intel_niosv_m_0_instruction_manager_address),                    //                    .address
		.instruction_manager_read          (intel_niosv_m_0_instruction_manager_read),                       //                    .read
		.data_manager_readdata             (intel_niosv_m_0_data_manager_readdata),                          //        data_manager.readdata
		.data_manager_waitrequest          (intel_niosv_m_0_data_manager_waitrequest),                       //                    .waitrequest
		.data_manager_readdatavalid        (intel_niosv_m_0_data_manager_readdatavalid),                     //                    .readdatavalid
		.data_manager_response             (intel_niosv_m_0_data_manager_response),                          //                    .response
		.data_manager_address              (intel_niosv_m_0_data_manager_address),                           //                    .address
		.data_manager_read                 (intel_niosv_m_0_data_manager_read),                              //                    .read
		.data_manager_write                (intel_niosv_m_0_data_manager_write),                             //                    .write
		.data_manager_writedata            (intel_niosv_m_0_data_manager_writedata),                         //                    .writedata
		.data_manager_byteenable           (intel_niosv_m_0_data_manager_byteenable),                        //                    .byteenable
		.data_manager_writeresponsevalid   (intel_niosv_m_0_data_manager_writeresponsevalid),                //                    .writeresponsevalid
		.dm_agent_address                  (mm_interconnect_0_intel_niosv_m_0_dm_agent_address),             //            dm_agent.address
		.dm_agent_read                     (mm_interconnect_0_intel_niosv_m_0_dm_agent_read),                //                    .read
		.dm_agent_readdata                 (mm_interconnect_0_intel_niosv_m_0_dm_agent_readdata),            //                    .readdata
		.dm_agent_write                    (mm_interconnect_0_intel_niosv_m_0_dm_agent_write),               //                    .write
		.dm_agent_writedata                (mm_interconnect_0_intel_niosv_m_0_dm_agent_writedata),           //                    .writedata
		.dm_agent_waitrequest              (mm_interconnect_0_intel_niosv_m_0_dm_agent_waitrequest),         //                    .waitrequest
		.dm_agent_readdatavalid            (mm_interconnect_0_intel_niosv_m_0_dm_agent_readdatavalid),       //                    .readdatavalid
		.dbg_reset_out_reset               (intel_niosv_m_0_dbg_reset_out_reset)                             //       dbg_reset_out.reset
	);

	altera_avalon_jtag_uart #(
		.readBufferDepth            (64),
		.readIRQThreshold           (8),
		.useRegistersForReadBuffer  (0),
		.useRegistersForWriteBuffer (0),
		.writeBufferDepth           (64),
		.writeIRQThreshold          (8),
		.printingMethod             (0),
		.FIFO_WIDTH                 (8),
		.WR_WIDTHU                  (6),
		.RD_WIDTHU                  (6),
		.write_le                   ("ON"),
		.read_le                    ("ON"),
		.HEX_WRITE_DEPTH_STR        (64),
		.HEX_READ_DEPTH_STR         (64),
		.legacySignalAllow          (0)
	) jtag_uart_0 (
		.clk            (pll_0_outclk0_clk),                                           //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                             //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                                     //               irq.irq
	);

	ccom_rx_onchip_memory2_0 onchip_memory2_0 (
		.clk        (pll_0_outclk0_clk),                                //   clk1.clk
		.address    (mm_interconnect_0_onchip_memory2_0_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_onchip_memory2_0_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_onchip_memory2_0_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_onchip_memory2_0_s1_write),      //       .write
		.readdata   (mm_interconnect_0_onchip_memory2_0_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_onchip_memory2_0_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_onchip_memory2_0_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),                   // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),               //       .reset_req
		.freeze     (1'b0)                                              // (terminated)
	);

	ccom_rx_pio_dxdy pio_dxdy (
		.clk      (pll_0_outclk0_clk),                      //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address  (mm_interconnect_0_pio_dxdy_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_dxdy_s1_readdata), //                    .readdata
		.in_port  (dxdy_export)                             // external_connection.export
	);

	ccom_rx_pio_dxdy pio_qpdp1 (
		.clk      (pll_0_outclk0_clk),                       //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),         //               reset.reset_n
		.address  (mm_interconnect_0_pio_qpdp1_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_qpdp1_s1_readdata), //                    .readdata
		.in_port  (qpdp1_export)                             // external_connection.export
	);

	ccom_rx_pio_dxdy pio_qpdp2 (
		.clk      (pll_0_outclk0_clk),                       //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),         //               reset.reset_n
		.address  (mm_interconnect_0_pio_qpdp2_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_qpdp2_s1_readdata), //                    .readdata
		.in_port  (qpdp2_export)                             // external_connection.export
	);

	ccom_rx_pio_status pio_status (
		.clk      (pll_0_outclk0_clk),                        //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),          //               reset.reset_n
		.address  (mm_interconnect_0_pio_status_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pio_status_s1_readdata), //                    .readdata
		.in_port  (status_export)                             // external_connection.export
	);

	ccom_rx_pll_0 pll_0 (
		.refclk   (clk50_clk),         //  refclk.clk
		.rst      (~reset_n_reset_n),  //   reset.reset
		.outclk_0 (pll_0_outclk0_clk), // outclk0.clk
		.locked   ()                   // (terminated)
	);

	ccom_rx_mm_interconnect_0 mm_interconnect_0 (
		.pll_0_outclk0_clk                                 (pll_0_outclk0_clk),                                              //                               pll_0_outclk0.clk
		.intel_niosv_m_0_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                                 // intel_niosv_m_0_reset_reset_bridge_in_reset.reset
		.intel_niosv_m_0_data_manager_address              (intel_niosv_m_0_data_manager_address),                           //                intel_niosv_m_0_data_manager.address
		.intel_niosv_m_0_data_manager_waitrequest          (intel_niosv_m_0_data_manager_waitrequest),                       //                                            .waitrequest
		.intel_niosv_m_0_data_manager_byteenable           (intel_niosv_m_0_data_manager_byteenable),                        //                                            .byteenable
		.intel_niosv_m_0_data_manager_read                 (intel_niosv_m_0_data_manager_read),                              //                                            .read
		.intel_niosv_m_0_data_manager_readdata             (intel_niosv_m_0_data_manager_readdata),                          //                                            .readdata
		.intel_niosv_m_0_data_manager_readdatavalid        (intel_niosv_m_0_data_manager_readdatavalid),                     //                                            .readdatavalid
		.intel_niosv_m_0_data_manager_write                (intel_niosv_m_0_data_manager_write),                             //                                            .write
		.intel_niosv_m_0_data_manager_writedata            (intel_niosv_m_0_data_manager_writedata),                         //                                            .writedata
		.intel_niosv_m_0_data_manager_response             (intel_niosv_m_0_data_manager_response),                          //                                            .response
		.intel_niosv_m_0_data_manager_writeresponsevalid   (intel_niosv_m_0_data_manager_writeresponsevalid),                //                                            .writeresponsevalid
		.intel_niosv_m_0_instruction_manager_address       (intel_niosv_m_0_instruction_manager_address),                    //         intel_niosv_m_0_instruction_manager.address
		.intel_niosv_m_0_instruction_manager_waitrequest   (intel_niosv_m_0_instruction_manager_waitrequest),                //                                            .waitrequest
		.intel_niosv_m_0_instruction_manager_read          (intel_niosv_m_0_instruction_manager_read),                       //                                            .read
		.intel_niosv_m_0_instruction_manager_readdata      (intel_niosv_m_0_instruction_manager_readdata),                   //                                            .readdata
		.intel_niosv_m_0_instruction_manager_readdatavalid (intel_niosv_m_0_instruction_manager_readdatavalid),              //                                            .readdatavalid
		.intel_niosv_m_0_instruction_manager_response      (intel_niosv_m_0_instruction_manager_response),                   //                                            .response
		.intel_niosv_m_0_dm_agent_address                  (mm_interconnect_0_intel_niosv_m_0_dm_agent_address),             //                    intel_niosv_m_0_dm_agent.address
		.intel_niosv_m_0_dm_agent_write                    (mm_interconnect_0_intel_niosv_m_0_dm_agent_write),               //                                            .write
		.intel_niosv_m_0_dm_agent_read                     (mm_interconnect_0_intel_niosv_m_0_dm_agent_read),                //                                            .read
		.intel_niosv_m_0_dm_agent_readdata                 (mm_interconnect_0_intel_niosv_m_0_dm_agent_readdata),            //                                            .readdata
		.intel_niosv_m_0_dm_agent_writedata                (mm_interconnect_0_intel_niosv_m_0_dm_agent_writedata),           //                                            .writedata
		.intel_niosv_m_0_dm_agent_readdatavalid            (mm_interconnect_0_intel_niosv_m_0_dm_agent_readdatavalid),       //                                            .readdatavalid
		.intel_niosv_m_0_dm_agent_waitrequest              (mm_interconnect_0_intel_niosv_m_0_dm_agent_waitrequest),         //                                            .waitrequest
		.intel_niosv_m_0_timer_sw_agent_address            (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_address),       //              intel_niosv_m_0_timer_sw_agent.address
		.intel_niosv_m_0_timer_sw_agent_write              (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_write),         //                                            .write
		.intel_niosv_m_0_timer_sw_agent_read               (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_read),          //                                            .read
		.intel_niosv_m_0_timer_sw_agent_readdata           (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_readdata),      //                                            .readdata
		.intel_niosv_m_0_timer_sw_agent_writedata          (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_writedata),     //                                            .writedata
		.intel_niosv_m_0_timer_sw_agent_byteenable         (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_byteenable),    //                                            .byteenable
		.intel_niosv_m_0_timer_sw_agent_readdatavalid      (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_readdatavalid), //                                            .readdatavalid
		.intel_niosv_m_0_timer_sw_agent_waitrequest        (mm_interconnect_0_intel_niosv_m_0_timer_sw_agent_waitrequest),   //                                            .waitrequest
		.jtag_uart_0_avalon_jtag_slave_address             (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_address),        //               jtag_uart_0_avalon_jtag_slave.address
		.jtag_uart_0_avalon_jtag_slave_write               (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_write),          //                                            .write
		.jtag_uart_0_avalon_jtag_slave_read                (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_read),           //                                            .read
		.jtag_uart_0_avalon_jtag_slave_readdata            (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_readdata),       //                                            .readdata
		.jtag_uart_0_avalon_jtag_slave_writedata           (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_writedata),      //                                            .writedata
		.jtag_uart_0_avalon_jtag_slave_waitrequest         (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_waitrequest),    //                                            .waitrequest
		.jtag_uart_0_avalon_jtag_slave_chipselect          (mm_interconnect_0_jtag_uart_0_avalon_jtag_slave_chipselect),     //                                            .chipselect
		.onchip_memory2_0_s1_address                       (mm_interconnect_0_onchip_memory2_0_s1_address),                  //                         onchip_memory2_0_s1.address
		.onchip_memory2_0_s1_write                         (mm_interconnect_0_onchip_memory2_0_s1_write),                    //                                            .write
		.onchip_memory2_0_s1_readdata                      (mm_interconnect_0_onchip_memory2_0_s1_readdata),                 //                                            .readdata
		.onchip_memory2_0_s1_writedata                     (mm_interconnect_0_onchip_memory2_0_s1_writedata),                //                                            .writedata
		.onchip_memory2_0_s1_byteenable                    (mm_interconnect_0_onchip_memory2_0_s1_byteenable),               //                                            .byteenable
		.onchip_memory2_0_s1_chipselect                    (mm_interconnect_0_onchip_memory2_0_s1_chipselect),               //                                            .chipselect
		.onchip_memory2_0_s1_clken                         (mm_interconnect_0_onchip_memory2_0_s1_clken),                    //                                            .clken
		.pio_dxdy_s1_address                               (mm_interconnect_0_pio_dxdy_s1_address),                          //                                 pio_dxdy_s1.address
		.pio_dxdy_s1_readdata                              (mm_interconnect_0_pio_dxdy_s1_readdata),                         //                                            .readdata
		.pio_qpdp1_s1_address                              (mm_interconnect_0_pio_qpdp1_s1_address),                         //                                pio_qpdp1_s1.address
		.pio_qpdp1_s1_readdata                             (mm_interconnect_0_pio_qpdp1_s1_readdata),                        //                                            .readdata
		.pio_qpdp2_s1_address                              (mm_interconnect_0_pio_qpdp2_s1_address),                         //                                pio_qpdp2_s1.address
		.pio_qpdp2_s1_readdata                             (mm_interconnect_0_pio_qpdp2_s1_readdata),                        //                                            .readdata
		.pio_status_s1_address                             (mm_interconnect_0_pio_status_s1_address),                        //                               pio_status_s1.address
		.pio_status_s1_readdata                            (mm_interconnect_0_pio_status_s1_readdata)                        //                                            .readdata
	);

	ccom_rx_irq_mapper irq_mapper (
		.clk           (pll_0_outclk0_clk),                   //       clk.clk
		.reset         (rst_controller_reset_out_reset),      // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),            // receiver0.irq
		.sender_irq    (intel_niosv_m_0_platform_irq_rx_irq)  //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_n_reset_n),                   // reset_in0.reset
		.clk            (pll_0_outclk0_clk),                  //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
